# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x12studentInformation\"\xe8\x01\n\x0bStudentList\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x14\n\x0cstudent_name\x18\x02 \x01(\t\x12?\n\x07student\x18\x03 \x03(\x0b\x32..studentInformation.StudentList.StudentDetails\x1an\n\x0eStudentDetails\x12\x31\n\x06result\x18\x01 \x01(\x0e\x32!.studentInformation.StudentResult\x12\x13\n\x0btotal_marks\x18\x02 \x01(\x05\x12\x14\n\x0cmarks_obtain\x18\x03 \x01(\x05*a\n\rStudentResult\x12\x08\n\x04PASS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x12\x10\n\x0cNOT_APPEARED\x10\x02\x12\x15\n\x11RESULT_UNDECLARED\x10\x03\x12\x13\n\x0fPASS_WITH_GRACE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STUDENTRESULT']._serialized_start=272
  _globals['_STUDENTRESULT']._serialized_end=369
  _globals['_STUDENTLIST']._serialized_start=38
  _globals['_STUDENTLIST']._serialized_end=270
  _globals['_STUDENTLIST_STUDENTDETAILS']._serialized_start=160
  _globals['_STUDENTLIST_STUDENTDETAILS']._serialized_end=270
# @@protoc_insertion_point(module_scope)
