# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcp_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etcp_data.proto\"U\n\x0bStudentList\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x14\n\x0cstudent_name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"=\n\x18StudentListMessagesGroup\x12!\n\x0bstudentList\x18\x01 \x03(\x0b\x32\x0c.StudentListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tcp_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STUDENTLIST']._serialized_start=18
  _globals['_STUDENTLIST']._serialized_end=103
  _globals['_RESPONSE']._serialized_start=105
  _globals['_RESPONSE']._serialized_end=132
  _globals['_STUDENTLISTMESSAGESGROUP']._serialized_start=134
  _globals['_STUDENTLISTMESSAGESGROUP']._serialized_end=195
# @@protoc_insertion_point(module_scope)
